/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Usuario
 */
public class MenuManager extends javax.swing.JFrame {

    /**
     * Creates new form MenuManager
     */
    public MenuManager() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Menú");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMenuAdiministrador = new javax.swing.JPanel();
        butDayReport = new javax.swing.JButton();
        butMonthlyReport = new javax.swing.JButton();
        butMachines = new javax.swing.JButton();
        butUsers = new javax.swing.JButton();
        panDataUsers = new javax.swing.JPanel();
        labPhoto = new javax.swing.JLabel();
        labPokerland = new javax.swing.JLabel();
        butLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panMenuAdiministrador.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        butDayReport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        butDayReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/report.png"))); // NOI18N
        butDayReport.setText("Report Day");
        butDayReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDayReportActionPerformed(evt);
            }
        });

        butMonthlyReport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        butMonthlyReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/reportMonth.png"))); // NOI18N
        butMonthlyReport.setText("Report Month");
        butMonthlyReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMonthlyReportActionPerformed(evt);
            }
        });

        butMachines.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        butMachines.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/machine.png"))); // NOI18N
        butMachines.setText("Machines");
        butMachines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMachinesActionPerformed(evt);
            }
        });

        butUsers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        butUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/users.png"))); // NOI18N
        butUsers.setText("Users");
        butUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butUsersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panMenuAdiministradorLayout = new javax.swing.GroupLayout(panMenuAdiministrador);
        panMenuAdiministrador.setLayout(panMenuAdiministradorLayout);
        panMenuAdiministradorLayout.setHorizontalGroup(
            panMenuAdiministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuAdiministradorLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(panMenuAdiministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(butMonthlyReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butDayReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butMachines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        panMenuAdiministradorLayout.setVerticalGroup(
            panMenuAdiministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuAdiministradorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butDayReport, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butMonthlyReport, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butMachines, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butUsers)
                .addGap(69, 69, 69))
        );

        panDataUsers.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        labPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/admon.png"))); // NOI18N

        labPokerland.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/LETRAS.PNG"))); // NOI18N

        butLogOut.setBackground(new java.awt.Color(204, 0, 0));
        butLogOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        butLogOut.setText("Sign  out ");
        butLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panDataUsersLayout = new javax.swing.GroupLayout(panDataUsers);
        panDataUsers.setLayout(panDataUsersLayout);
        panDataUsersLayout.setHorizontalGroup(
            panDataUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDataUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labPokerland)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butLogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(labPhoto)
                .addContainerGap())
        );
        panDataUsersLayout.setVerticalGroup(
            panDataUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
            .addGroup(panDataUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDataUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDataUsersLayout.createSequentialGroup()
                        .addComponent(butLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panDataUsersLayout.createSequentialGroup()
                        .addComponent(labPokerland, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panMenuAdiministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panDataUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panDataUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panMenuAdiministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butDayReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDayReportActionPerformed
        ReportDay Wconnect = new ReportDay();
        Wconnect.setVisible(true);
        dispose();
    }//GEN-LAST:event_butDayReportActionPerformed

    private void butLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLogOutActionPerformed
        Login Wconnect = new Login();       
        Wconnect.setVisible(true);        
        dispose();
    }//GEN-LAST:event_butLogOutActionPerformed

    private void butMonthlyReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMonthlyReportActionPerformed
        ReportMonth Wconnect = new ReportMonth();
        Wconnect.setVisible(true);
        dispose();
    }//GEN-LAST:event_butMonthlyReportActionPerformed

    private void butMachinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMachinesActionPerformed
        AddDeleteMachines Wconnect = new AddDeleteMachines();
        Wconnect.setVisible(true);
        dispose();
    }//GEN-LAST:event_butMachinesActionPerformed

    private void butUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butUsersActionPerformed
        AddDeletedUsers Wconnect = new AddDeletedUsers();
        Wconnect.setVisible(true);
        dispose();
    }//GEN-LAST:event_butUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butDayReport;
    private javax.swing.JButton butLogOut;
    private javax.swing.JButton butMachines;
    private javax.swing.JButton butMonthlyReport;
    private javax.swing.JButton butUsers;
    private javax.swing.JLabel labPhoto;
    private javax.swing.JLabel labPokerland;
    private javax.swing.JPanel panDataUsers;
    private javax.swing.JPanel panMenuAdiministrador;
    // End of variables declaration//GEN-END:variables
}
